[package]
name = "rssr-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["std", "clock", "serde"] }
dirs = "7.0.0"
dom_smoothie = "0.18.1"
encoding_rs = "0.8.40"
feed-rs = "2.4.0"
htmd = "0.5.5"
http = "1.5.0"
quick-xml = "0.42.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
sha2 = "0.11.0"
ureq = { version = "3.4.1", default-features = false, features = ["rustls", "gzip"] }
